apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-efficiency-service
  labels:
    app: developer-efficiency-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: developer-efficiency-service
  template:
    metadata:
      labels:
        app: developer-efficiency-service
    spec:
      containers:
      - name: developer-efficiency-service
        image: acr-developeriq:developer-efficiency-service
        ports:
        - containerPort: 3000
