apiVersion: v1
kind: Service
metadata:
    name: developer-efficiency-service
spec:
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 
    selector:
        app: developer-efficiency-service